version: '3.4'

services:
  app.taxajuros:
    container_name: api-taxa-juros
    build:
      context: .
      dockerfile: TaxaDeJurosAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
        - "8080:80"

  app.calculajuros:
    container_name: api-calcula-juros
    build:
      context: .
      dockerfile: CalculaJurosAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
         - "8081:80"